title: Science Mom
description: Hands-on science curriculum for curious kids.
url: "https://science.mom"
baseurl: ""
timezone: America/Anchorage

# Keep this simple; you can add collections later.
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/

include:
  - .htaccess

exclude:
  - _legacy
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
