# Site settings
title: Jenny Ballif
email: jenballif@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Science Mom, Writer, Language Enthusiast 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jennyballif.github.io" # the base hostname & protocol for your site
owner:            
  name:           Jenny Ballif
  email:          jenballif@gmail.com
  facebook:         jenny.ballif.5
  twitter:          JennyBallif
  github_username:  jennyballif
  disqus_shortname: jennyballif
  google_plus:    jenballif

# post sharing
twitter:
  username: JennyBallif

# Build settings







links:
  - title: Science Mom
    url: /sciencemom
  - title: Contact
    url: /contact
    
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
timezone:    America/Los_Angeles
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    12
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

    

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class





prose:
  rooturl: '_posts'
  siteurl: 'https://jennyballif.github.io/' #'http://hmfaysal.github.io/Notepad/'
  relativeLinks: 'https://jennyballif.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"       
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Title"
      - name: "description"
        field:
          element: "text"
          label: "Description for twitter"
          placeholder: "Enter post description for facebook or twitter"
      - name: "headline"
        field:
          element: "textarea"
          label: "Headline for the blog feed"
          placeholder: "Come explore cohesion and the basic physics of forces with <b>The Gravity Defying Lid</b>, a <b>Magic Screen</b>, and <b>Hot and Cold Water Cups</b>."
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Math"
              value: math
            - name: "Teaching"
              value: teaching
            - name: "Fun"
              value: fun
            - name: "Writing"
              value: writing
            - name: "Interesting"
              value: interesting
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image (should be square for twitter card)"
          placeholder: "somefile.jpg"
      - name: "videofeature"
        field:
          element: "text"
          label: "Featured Video youtube embed link"
          placeholder: "https://www.youtube.com/embed/iwqUhD47o14"
      - name: "sciencemom"
        field:
          element: "checkbox"
          label: "Science Mom"
          value: true
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: true
      - name: "folder"
        field:
          element: "text"
          label: "Image Folder"
          placeholder: "SMG1"
      - name: "sciencemomguideimage"
        field:
          element: "text"
          label: "Science Mom Guide Image"
          placeholder: "someotherfile.jpg"
      - name: "experiment1title"
        field:
          element: "text"
          label: "Experiment 1 Title"
          placeholder: "Gravity Defying Lid"
      - name: "experiment1time"
        field:
          element: "text"
          label: "Experiment 1 Time"
          placeholder: "10 min"
      - name: "experiment1supplies"
        field:
          element: "textarea"
          label: "Experiment 1 Supplies"
          placeholder: "1 cup water"
      - name: "experiment1concepts"
        field:
          element: "textarea"
          label: "Experiment 1 Concepts"
          placeholder: "Properties of water: cohesion"
      - name: "experiment1image"
        field:
          element: "text"
          label: "Experiment 1 Image"
          placeholder: "somefile.jpg"
      - name: "experiment2title"
        field:
          element: "text"
          label: "Experiment 2 Title"
          placeholder: "Gravity Defying Lid"
      - name: "experiment2time"
        field:
          element: "text"
          label: "Experiment 2 Time"
          placeholder: "10 min"
      - name: "experiment2supplies"
        field:
          element: "textarea"
          label: "Experiment 2 Supplies"
          placeholder: "1 cup water"
      - name: "experiment2concepts"
        field:
          element: "textarea"
          label: "Experiment 2 Concepts"
          placeholder: "Properties of water: cohesion"
      - name: "experiment2image"
        field:
          element: "text"
          label: "Experiment 2 Image"
          placeholder: "somefile.jpg"
      - name: "experiment3title"
        field:
          element: "text"
          label: "Experiment 3 Title"
          placeholder: "Gravity Defying Lid"
      - name: "experiment3time"
        field:
          element: "text"
          label: "Experiment 3 Time"
          placeholder: "10 min"
      - name: "experiment3supplies"
        field:
          element: "textarea"
          label: "Experiment 3 Supplies"
          placeholder: "1 cup water"
      - name: "experiment3concepts"
        field:
          element: "textarea"
          label: "Experiment 3 Concepts"
          placeholder: "Properties of water: cohesion"
      - name: "experiment3image"
        field:
          element: "text"
          label: "Experiment 3 Image"
          placeholder: "somefile.jpg"
      - name: "guide0"
        field:
          element: "text"
          label: "Wide image"
          placeholder: "SMG1wide.png"
      - name: "guide1"
        field:
          element: "text"
          label: "8.5x11 pdf file"
          placeholder: "SMG1-8.5x11.pdf"
      - name: "guide2"
        field:
          element: "text"
          label: "11x17 pdf file"
          placeholder: "SMG1-11x17.pdf"
      - name: "guide3"
        field:
          element: "text"
          label: "A4 pdf file"
          placeholder: "SMG1-A4.pdf"
      - name: "guide4"
        field:
          element: "text"
          label: "A3 pdf file"
          placeholder: "SMG1-A3.pdf"


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

